# Generated by Django 4.2.2 on 2023-06-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notespad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='note_folder',
            new_name='note',
        ),
    ]
